// @flow

export const SPOTIFY = {
  INITIALIZE_REQUEST: 'spotify/INITIALIZE_REQUEST',
  INITIALIZE_RESPONSE: 'spotify/INITIALIZE_RESPONSE',
  LOGIN_REQUEST: 'spotify/LOGIN_REQUEST',
  LOGIN_RESPONSE: 'spotify/LOGIN_RESPONSE',
  LOGOUT_REQUEST: 'spotify/LOGOUT_REQUEST',
  LOGOUT_RESPONSE: 'spotify/LOGOUT_RESPONSE',
}
